title: Internet Girlfriend Club
email: your-email@domain.com
description: > #
baseurl: /
markdown: kramdown
custom_theme: overkyll-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  volume1:
    output: true
  volume2:
    output: true
  volume3:
    output: true
  volume4:
    output: true
  volume5:
    output: true
  volume6:
    output: true
  volume7:
    output: true
  volume8:
    output: true
  volume9:
    output: true
  volume10:
    output: true
  volume11:
    output: true
  volume12:
    output: true