title: Internet Girlfriend Club
email: your-email@domain.com
description: > #
baseurl: /
markdown: kramdown
custom_theme: overkyll-jekyll-theme
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  chapter01:
    output: true
